name: CI
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  rust_check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - uses: davidB/rust-cargo-make@v1
      - uses: taiki-e/install-action@nextest

      - name: Run cargo make check
        run: |
          cargo make check

      - name: Spell Check
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        uses: crate-ci/typos@master

      - name: Audit
        uses: actions-rust-lang/audit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
