name: Publish Docker

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
env:
  IMAGE_NAME: rustmcp/filesystem

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ inputs.version }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Echo Pushed Tags
        run: |
          echo "Published:"
          echo " - ${{ env.IMAGE_NAME }}:${{ inputs.version }}"
          echo " - ${{ env.IMAGE_NAME }}:latest"
